version: '3'

networks:
  gitea:
    external: false

volumes:
  web:
    driver: local
  db:
    driver: local

services:
  web:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - USER_UID=163
      - USER_GID=163
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=KJIwtn8xYih0
    volumes:
      - web:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh:/data/git/.ssh
    networks:
      - gitea
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=eqxdTM4zB1Ch
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=KJIwtn8xYih0
    networks:
      - gitea
    volumes:
      - db:/var/lib/mysql
